export const LOAD_RESERVATION="LOAD_RESERVATION"
export const FAIL_RESERVATION="FAIL_RESERVATION"

export const ADD_RESERVATION="ADD_RESERVATION"

export const GET_DRIVER_REQUEST="GET_DRIVER_REQUEST"

export const GET_CUSTOMER_REQUEST="GET_CUSTOMER_REQUEST"

export const GET_ACCEPTED_REQUEST="GET_ACCEPTED_REQUEST"